services:
  gimp2:
    build:
      context: .
      args:
        UID: ${UID}
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/gimp/.Xauthority
    user: "${UID}:${GID}"
    volumes:
      - "./:/gimp:rw"
      - ~/.Xauthority:/home/gimp/.Xauthority:ro
    network_mode: host
